api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    doctrine:
        enabled: true
    formats:
        json:
            mime_types: [ 'application/json' ]
#        jsonld:
#            mime_types: [ 'application/ld+json' ]
#        jsonhal:
#            mime_types: [ 'application/hal+json' ]

