security:
    password_hashers:
        App\Entity\Security\VermittlerLogin: 'bcrypt'
        App\Entity\Security\UserLogin: 'bcrypt'
    enable_authenticator_manager: true
    providers:
        users:
            entity:
                class: App\Entity\Security\VermittlerLogin
                property: email
    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false
        main:
            stateless: true
            provider: users
            json_login:
                check_path: auth
                username_path: email
                password_path: passwd
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
    access_control:
        - { path: ^/foo/login, roles: PUBLIC_ACCESS }
        - { path: ^/docs, roles: PUBLIC_ACCESS }
        - { path: ^/foo/adressen.*, roles: ROLE_USER, methods:[GET] }
        - { path: ^/foo/kunden.*, roles: ROLE_USER, methods:[GET] }
        - { path: ^/foo/user.*, roles: ROLE_USER, methods:[GET] }
