security:
    password_hashers:
        App\Entity\VermittlerUser:
            algorithm: auto
    providers:
        users_in_memory: { memory: null }
        jwt:
            entity:
                class: App\Entity\VermittlerUser
                property: email

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            provider: 'jwt'
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/foo
            stateless: true
            provider: 'jwt'
            jwt: ~

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_memory

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/foo/docs, roles: PUBLIC_ACCESS }
        - { path: ^/foo, roles: IS_AUTHENTICATED_FULLY }
