api_platform:
    resource: .
    type: api_platform
    prefix: /foo
# get redirect name to api route
api_foo:
    path: /foo
# permanently route root-page to api
root:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /foo
        permanent: true