controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
api_login_check:
  path: /auth
  controller: App\Controller\AuthenticationController::getTokenUser
kunde_adressen:
  path: /foo/kunden/{id}/adressen
  controller: App\Controller\SubGetCollection\KundeSubCollectionController::getAdressen
  methods: [GET]

kunde_users:
  path: foo/kunden/{id}/user
  controller: App\Controller\SubGetCollection\KundeSubCollectionController::getUsers
  methods: [GET]

kunde_adresse_details:
  path: foo/kunden/{id}/adressen/{adresseId}/details
  controller: App\Controller\SubGetCollection\KundeSubCollectionController::getAdresseDetails
  methods: [GET]